/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { WardrobeItem } from './types';

export const defaultWardrobe: WardrobeItem[] = [
  // ==========================================
  // --- VESTUÁRIO (CAMISAS, POLOS, BLAZERS, CALÇAS, ETC.) ---
  // ==========================================
  {
    id: 'em-vest-01',
    name: 'Camisa Linho Puro Milano Slim',
    category: 'Vestuário',
    subCategory: 'Camisas',
    brand: 'Enzo Milano',
    price: 'R$ 489,00',
    installment: 'em até 6x de R$ 81,50 sem juros',
    composition: '100% Linho Europeu Importado',
    description: 'Camisa confeccionada em fibra de linho nobre com modelagem slim fit contemporânea. Toque arejado e sofisticado com botões em madrepérola.',
    isBestSeller: true,
    url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-02',
    name: 'Blazer Alfaiataria Navy Italiano',
    category: 'Vestuário',
    subCategory: 'Blazers',
    brand: 'Enzo Milano',
    price: 'R$ 1.190,00',
    installment: 'em até 10x de R$ 119,00 sem juros',
    composition: '98% Lã Fria Super 120s, 2% Elastano',
    description: 'Blazer estruturado com corte italiano clássico, forro acetinado personalizado e fendas laterais. Ideal para composições formais e smart-casual.',
    isBestSeller: true,
    url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-03',
    name: 'Polo Piquet Algodão Pima Black',
    category: 'Vestuário',
    subCategory: 'Polos',
    brand: 'Enzo Milano',
    price: 'R$ 349,00',
    installment: 'em até 5x de R$ 69,80 sem juros',
    composition: '100% Algodão Pima Peruano',
    description: 'Polo clássica com toque aveludado e durabilidade ímpar do algodão pima. Gola estruturada em ribana e abertura frontal sutil.',
    url: 'https://images.unsplash.com/photo-1625910513413-7e2898b96d9e?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-04',
    name: 'Jaqueta Suede Toque Aveludado',
    category: 'Vestuário',
    subCategory: 'Jaquetas',
    brand: 'Enzo Milano',
    price: 'R$ 899,00',
    installment: 'em até 8x de R$ 112,37 sem juros',
    composition: '100% Couro Sintético Suede Premium',
    description: 'Jaqueta bomber em camurça suede com zíper metálico reforçado e punhos ajustados. Peça icônica para os dias de meia-estação.',
    isNew: true,
    url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-05',
    name: 'Camisa Maquinetada Algodão Branco',
    category: 'Vestuário',
    subCategory: 'Camisas',
    brand: 'Enzo Milano',
    price: 'R$ 429,00',
    installment: 'em até 6x de R$ 71,50 sem juros',
    composition: '100% Algodão Egípcio Fio 80',
    description: 'Camisa social branca com discreto micro-desenho maquinetado. Perfeita para reuniões de negócios e trajes sob medida.',
    url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-06',
    name: 'Calça Chino Alfaiataria Khaki',
    category: 'Vestuário',
    subCategory: 'Calças',
    brand: 'Enzo Milano',
    price: 'R$ 449,00',
    installment: 'em até 6x de R$ 74,83 sem juros',
    composition: '97% Algodão Satin, 3% Spandex',
    description: 'Calça chino com bolsos faca e acabamento interno de alfaiataria. Conforto elástico com aparência refinada.',
    isBestSeller: true,
    url: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-07',
    name: 'Jaqueta Couro Legítimo Biker',
    category: 'Vestuário',
    subCategory: 'Jaquetas',
    brand: 'Enzo Milano',
    price: 'R$ 1.890,00',
    installment: 'em até 10x de R$ 189,00 sem juros',
    composition: '100% Couro Bovino Pelica Legítimo',
    description: 'Couro nobre macio e encorpado com forro térmico acetinado, fechamento assimétrico e metais na tonalidade chumbo.',
    isNew: true,
    url: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-08',
    name: 'Suéter Tricot Merino Gola V',
    category: 'Vestuário',
    subCategory: 'Suéteres',
    brand: 'Enzo Milano',
    price: 'R$ 529,00',
    installment: 'em até 6x de R$ 88,16 sem juros',
    composition: '80% Lã Merino Australiana, 20% Seda',
    description: 'Tricot em ponto fino com toque acetinado e termorregulação natural. Ajusta-se perfeitamente sobre camisas sociais.',
    url: 'https://images.unsplash.com/photo-1614975058789-41316d0e2e9c?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-09',
    name: 'Calça Jeans Slim Fit Deep Blue',
    category: 'Vestuário',
    subCategory: 'Calças',
    brand: 'Enzo Milano',
    price: 'R$ 499,00',
    installment: 'em até 6x de R$ 83,16 sem juros',
    composition: '98% Algodão Premium, 2% Elastano T400',
    description: 'Denim escuro com lavagem discreta e costuras em ocre. Mantém o formato original ao longo de todo o dia.',
    url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-10',
    name: 'Bermuda Linho Alfaiataria Areia',
    category: 'Vestuário',
    subCategory: 'Bermudas',
    brand: 'Enzo Milano',
    price: 'R$ 369,00',
    installment: 'em até 5x de R$ 73,80 sem juros',
    composition: '55% Linho Puro, 45% Algodão',
    description: 'Bermuda com cós tradicional e passantes, ideal para almoços ao ar livre e passeios à beira-mar com mocassim ou sapatênis.',
    url: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-11',
    name: 'Colete Puffer Ultraleve Marinho',
    category: 'Vestuário',
    subCategory: 'Coletes',
    brand: 'Enzo Milano',
    price: 'R$ 579,00',
    installment: 'em até 6x de R$ 96,50 sem juros',
    composition: '100% Poliamida com enchimento térmico Down',
    description: 'Colete com pespontos horizontais, gola alta e bolsos com zíper embutido. Compacto e muito confortável.',
    url: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-vest-12',
    name: 'Camiseta Pima Essential Off-White',
    category: 'Vestuário',
    subCategory: 'Camisetas',
    brand: 'Enzo Milano',
    price: 'R$ 259,00',
    installment: 'em até 4x de R$ 64,75 sem juros',
    composition: '100% Algodão Pima Peruano Certificado',
    description: 'Camiseta gola careca básica refinada. Tecido sedoso e encorpado que não forma bolinhas e veste com caimento impecável.',
    url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=700&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // --- CALÇADOS (SAPATÊNIS, MOCASSINS, BOTAS, ETC.) ---
  // ==========================================
  {
    id: 'em-calc-01',
    name: 'Sapatênis Couro Legítimo Nobuck Off-White',
    category: 'Calçados',
    subCategory: 'Sapatênis',
    brand: 'Enzo Milano',
    price: 'R$ 689,00',
    installment: 'em até 6x de R$ 114,83 sem juros',
    composition: '100% Couro Bovino Nobuck Macio',
    description: 'Sapatênis com solado blaqueado em borracha natural, forração interna em pelica absorvente e palmilha em gel anatômica.',
    isBestSeller: true,
    url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-calc-02',
    name: 'Mocassim Drive Camurça Tobacco',
    category: 'Calçados',
    subCategory: 'Mocassim',
    brand: 'Enzo Milano',
    price: 'R$ 599,00',
    installment: 'em até 6x de R$ 99,83 sem juros',
    composition: 'Camurça Natural Italiana com cravos emborrachados',
    description: 'Mocassim clássico estilo italiano driver, com costura manual no bico e conforto excepcional para usar sem meias.',
    isBestSeller: true,
    url: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-calc-03',
    name: 'Bota Chelsea Couro Craquelê Rústico',
    category: 'Calçados',
    subCategory: 'Botas',
    brand: 'Enzo Milano',
    price: 'R$ 799,00',
    installment: 'em até 8x de R$ 99,87 sem juros',
    composition: '100% Couro Legítimo Estonado',
    description: 'Bota chelsea com elásticos laterais duplos reforçados, puxador traseiro e solado tratorado antiderrapante.',
    isNew: true,
    url: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-calc-04',
    name: 'Sapato Social Oxford Preto Pelica',
    category: 'Calçados',
    subCategory: 'Sapatos',
    brand: 'Enzo Milano',
    price: 'R$ 849,00',
    installment: 'em até 8x de R$ 106,12 sem juros',
    composition: 'Couro Bovino Flor Integral com Solado em Couro',
    description: 'Oxford legítimo com amarração fechada e acabamento polido à mão. Essencial para costumes, smokings e trajes de gala.',
    url: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-calc-05',
    name: 'Tênis Minimalista Couro All Black',
    category: 'Calçados',
    subCategory: 'Tênis',
    brand: 'Enzo Milano',
    price: 'R$ 629,00',
    installment: 'em até 6x de R$ 104,83 sem juros',
    composition: '100% Couro Premium Monocromático',
    description: 'Design limpo e sem logotipos evidentes. Versatilidade máxima para combinar com calças de alfaiataria ou jeans.',
    url: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-calc-06',
    name: 'Mocassim Penny Loafer Preto Clássico',
    category: 'Calçados',
    subCategory: 'Mocassim',
    brand: 'Enzo Milano',
    price: 'R$ 729,00',
    installment: 'em até 7x de R$ 104,14 sem juros',
    composition: 'Couro Bovino Selecionado com Palmilha Acolchoada',
    description: 'Penny loafer atemporal com cinta transpassada sobre o peito do pé. Eleva qualquer composição casual elegante.',
    url: 'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-calc-07',
    name: 'Sapatênis Casual Knit Comfort Marinho',
    category: 'Calçados',
    subCategory: 'Sapatênis',
    brand: 'Enzo Milano',
    price: 'R$ 549,00',
    installment: 'em até 5x de R$ 109,80 sem juros',
    composition: 'Trama Knit Respirável com detalhes em Couro',
    description: 'Combinação de tecnologia em tecido elástico respirável e acabamentos refinados em couro legítimo.',
    url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=700&auto=format&fit=crop&q=80',
  },

  // ==========================================
  // --- ACESSÓRIOS (CINTOS, CARTEIRAS, ÓCULOS, RELÓGIOS, ETC.) ---
  // ==========================================
  {
    id: 'em-acess-01',
    name: 'Cinto Couro Dupla Face Preto/Marrom',
    category: 'Acessórios',
    subCategory: 'Cintos',
    brand: 'Enzo Milano',
    price: 'R$ 299,00',
    installment: 'em até 4x de R$ 74,75 sem juros',
    composition: '100% Couro Bovino com fivela giratória fosca',
    description: 'Cinto versátil com acabamento pespontado que permite alternar entre o lado preto e o marrom café em um único clique.',
    isBestSeller: true,
    url: 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-acess-02',
    name: 'Óculos de Sol Milano Polarizado Tortoise',
    category: 'Acessórios',
    subCategory: 'Óculos',
    brand: 'Enzo Milano',
    price: 'R$ 489,00',
    installment: 'em até 6x de R$ 81,50 sem juros',
    composition: 'Armação em acetato italiano e lentes polarizadas UV400',
    description: 'Armação tartaruga clássica com hastes reforçadas e lentes de alto contraste que reduzem reflexos nocivos.',
    isNew: true,
    url: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-acess-03',
    name: 'Carteira Slim Couro Legítimo Café',
    category: 'Acessórios',
    subCategory: 'Carteiras',
    brand: 'Enzo Milano',
    price: 'R$ 219,00',
    installment: 'em até 3x de R$ 73,00 sem juros',
    composition: 'Couro Fóssil Premium com proteção RFID',
    description: 'Perfil ultrafino projetado para bolsos dianteiros, com espaço para cartões, CNH e cédulas dobradas.',
    url: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-acess-04',
    name: 'Boné Suede Milano Aba Curva Chumbo',
    category: 'Acessórios',
    subCategory: 'Bonés',
    brand: 'Enzo Milano',
    price: 'R$ 199,00',
    installment: 'em até 3x de R$ 66,33 sem juros',
    composition: 'Camurça Suede e fecho traseiro metálico personalizado',
    description: 'Boné com toque aveludado e bordado tonal minimalista do monograma Milano na lateral.',
    url: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-acess-05',
    name: 'Mochila Executiva Couro Nobre Black',
    category: 'Acessórios',
    subCategory: 'Mochilas',
    brand: 'Enzo Milano',
    price: 'R$ 1.290,00',
    installment: 'em até 10x de R$ 129,00 sem juros',
    composition: '100% Couro Genuíno Floater',
    description: 'Compartimento acolchoado para notebook de até 16 polegadas, alças ergonômicas antitranspirantes e fixador para mala de viagem.',
    url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=700&auto=format&fit=crop&q=80',
  },
  {
    id: 'em-acess-06',
    name: 'Pulseira Couro Trançado com Fecho Magnético',
    category: 'Acessórios',
    subCategory: 'Pulseiras',
    brand: 'Enzo Milano',
    price: 'R$ 169,00',
    installment: 'em até 3x de R$ 56,33 sem juros',
    composition: 'Couro Legítimo Trançado e Aço Inox 316L',
    description: 'Acessório discreto e marcante que agrega sofisticação aos punhos em composições com camisas ou polos.',
    url: 'https://images.unsplash.com/photo-1611591475152-478d13b6676f?w=700&auto=format&fit=crop&q=80',
  },
];
